# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='experience_needed',
            field=models.CharField(max_length=50),
        ),
    ]
